### ISSUE TITLE
Missing module 'ebook_converter.ebooks.docx.dump'

### ISSUE THREAD

**Issue by zagura** [gryf/ebook-converter#1]
When running conversion using docx module, python throws an exception:
```python3
Traceback (most recent call last):
  File "/path/bin/ebook-converter", line 11, in <module>
    load_entry_point('ebook-converter==4.9.1', 'console_scripts', 'ebook-converter')()
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/main.py", line 8, in run
    sys.exit(main())
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/ebooks/conversion/cli.py", line 364, in main
    parser, plumber = create_option_parser(args, log)
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/ebooks/conversion/cli.py", line 311, in create_option_parser
    from ebook_converter.ebooks.conversion.plumber import Plumber
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/ebooks/conversion/plumber.py", line 9, in <module>
    from ebook_converter.customize.ui import input_profiles, output_profiles, \
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/customize/ui.py", line 12, in <module>
    from ebook_converter.customize import builtins
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/customize/builtins.py", line 651, in <module>
    from ebook_converter.ebooks.conversion.plugins.docx_output import DOCXOutput
  File "/path/lib/python3.7/site-packages/ebook_converter-4.9.1-py3.7.egg/ebook_converter/ebooks/conversion/plugins/docx_output.py", line 7, in <module>
    from ebook_converter.ebooks.docx.dump import do_dump
ModuleNotFoundError: No module named 'ebook_converter.ebooks.docx.dump'
```
https://github.com/gryf/ebook-converter/blob/ce89f5c9d12b2ba76189690a02249407686892ed/ebook_converter/ebooks/conversion/plugins/docx_output.py#L7
In current tree, there is only `do_dump` call, no `dump.py` file or any other providing `do_dump` function.

**Comment by gryf** [comment]
Ha. For some reason, I forgot to add `dump` module to the repo, although I do have it locally, perhaps this is the reason, why my smoke tests has run just fine. Commit 7419954 will fix it.

**Comment by zagura** [comment]
Thanks for quick fix :)
