### ISSUE TITLE
SyntaxError: invalid syntax Error While trying a conversion

### ISSUE THREAD

**Issue by keshavbhatt** [gryf/ebook-converter#2]
Am getting the following error when trying :
```
ebook-converter o.docx o.lrf
Traceback (most recent call last):
  File "/home/bulld/ebook-convert/venv/bin/ebook-converter", line 5, in <module>
    from ebook_converter.main import run
  File "/home/bulld/ebook-convert/venv/lib/python3.5/site-packages/ebook_converter/__init__.py", line 16, in <module>
    from ebook_converter.ebooks.html_entities import html5_entities
  File "/home/bulld/ebook-convert/venv/lib/python3.5/site-packages/ebook_converter/ebooks/__init__.py", line 124
    print(f'Failed to render {path_to_html}')
                                           ^
SyntaxError: invalid syntax
```

**Comment by gryf** [comment]
I'm sorry, but Python 3.5 and below is not supported.
